## Credit Card Fraud Detection

importing the dependencies

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [35]:
credits=pd.read_csv('creditcard.csv')

In [36]:
credits.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [37]:
credits.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [38]:
credits.shape

(284807, 31)

In [39]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [40]:
credits.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [41]:
credits['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [42]:
credits.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [43]:
Fraud=credits[credits['Class']==1]
legit=credits[credits['Class']==0]

In [44]:
Fraud['Amount'].describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [45]:
legit['Amount'].describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [46]:
credits.groupby('Class').describe()

           Time                                                       \
          count          mean           std    min      25%      50%
Class
0      284315.0  94838.202258  47484.015786    0.0  54230.0  84711.0
1         492.0  80746.806911  47835.365138  406.0  41241.5  75568.5

                                 V1            ...       V28             \
            75%       max     count      mean  ...       75%        max
Class                                          ...
0      139333.0  172792.0  284315.0  0.008258  ...  0.077962  33.847808
1      128483.0  170348.0     492.0 -4.771948  ...  0.381152   1.779364

         Amount
          count        mean         std  min   25%    50%     75%       max
Class
0      284315.0   88.291022  250.105092  0.0  5.65  22.00   77.05  25691.16
1         492.0  122.211321  256.683288  0.0  1.00   9.25  105.89   2125.87

[2 rows x 240 columns]

## Balancing the data

Build a sample dataset containing similar distribution of normal and fraudulent transaction

In [47]:
legit_sample=legit.sample(n=492)

In [48]:
new_data=pd.concat([legit_sample,Fraud],axis=0)

In [49]:
new_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
118514,75109.0,1.296218,0.043078,-0.235619,0.057475,0.528526,0.769875,-0.215934,0.240763,0.032972,...,-0.302105,-0.907332,-0.049046,-1.739890,0.315586,0.216970,-0.024298,-0.014063,1.29,0
181249,124890.0,-0.671418,-1.384084,-0.135936,-2.900340,1.699060,3.895513,-0.854134,0.755340,-1.931814,...,-0.154787,0.123043,-0.001967,0.699671,-0.152048,0.014170,0.128654,0.063377,112.00,0
251411,155339.0,2.034648,-0.286046,-1.718034,0.490922,-0.042336,-1.338673,0.337843,-0.284430,0.805053,...,-0.050991,-0.115996,0.086952,-0.097540,0.069117,0.574933,-0.116651,-0.079687,29.99,0
41519,40716.0,-0.802463,0.955308,1.510976,-0.004391,0.324109,-0.780759,0.915802,-0.076438,-0.772316,...,0.203686,0.485182,-0.255455,0.541181,0.088963,-0.546777,-0.016560,0.110981,24.21,0
244468,152368.0,-0.946109,0.556075,0.248275,-0.559148,1.242580,-0.983783,0.868188,-0.119472,-0.494935,...,0.211626,0.529205,-0.622133,-0.402068,1.142486,0.030561,-0.183807,-0.024871,46.00,0

In [50]:
new_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [51]:
new_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95385.341463,-0.084533,-0.086494,0.106309,0.033106,0.022339,0.119976,0.081034,0.018534,0.016750,...,-0.051988,-0.013860,0.000873,0.016321,-0.030498,0.006909,0.017804,-0.018419,-0.037195,91.435366
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data in features and target variable

In [52]:
x=new_data.drop('Class',axis=1)
y=new_data['Class']

In [53]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20,stratify=y, random_state=42)

In [54]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [55]:
Y_train_pred=model.predict(X_train)
train_acc=accuracy_score(Y_train_pred,y_train)

In [56]:
train_acc

0.9351969504447268

In [57]:
Y_test_pred=model.predict(X_test)
test_acc=accuracy_score(Y_test_pred,y_test)

In [58]:
test_acc

0.9441624365482234

## Hyperparameter Tuning

In [59]:
from sklearn.model_selection import GridSearchCV

In [60]:
classifier=GridSearchCV(model,
                        {
                            'penalty':['l1','l2','elasticnet','none'],
                            'C':[0.01,0.1,1,10,100],
                            'l1_ratio':[0,0.5,1]
                        },cv=5)

In [61]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 10, 100], 'l1_ratio': [0, 0.5, 1],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none']})

In [62]:
pd.DataFrame(classifier.cv_results_).sort_values('mean_test_score',ascending=False).head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_l1_ratio,param_penalty,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
1,0.046770,0.023906,0.008418,0.007422,0.01,0.0,l2,"{'C': 0.01, 'l1_ratio': 0, 'penalty': 'l2'}",0.979695,0.944162,0.913706,0.944162,0.887755,0.933896,0.031129,1
5,0.016442,0.001709,0.001406,0.000797,0.01,0.5,l2,"{'C': 0.01, 'l1_ratio': 0.5, 'penalty': 'l2'}",0.979695,0.944162,0.913706,0.944162,0.887755,0.933896,0.031129,1
9,0.015773,0.000983,0.001206,0.000986,0.01,1.0,l2,"{'C': 0.01, 'l1_ratio': 1, 'penalty': 'l2'}",0.979695,0.944162,0.913706,0.944162,0.887755,0.933896,0.031129,1
37,0.016257,0.001960,0.001212,0.001068,10.00,0.0,l2,"{'C': 10, 'l1_ratio': 0, 'penalty': 'l2'}",0.974619,0.923858,0.908629,0.934010,0.923469,0.932917,0.022367,4
45,0.016402,0.006716,0.000896,0.001108,10.00,1.0,l2,"{'C': 10, 'l1_ratio': 1, 'penalty': 'l2'}",0.974619,0.923858,0.908629,0.934010,0.923469,0.932917,0.022367,4

Model after Tuning

In [63]:
Hyper_model=LogisticRegression(C=0.01,l1_ratio=0,penalty='l2')

In [64]:
Hyper_model.fit(X_train,y_train)

LogisticRegression(C=0.01, l1_ratio=0)

In [67]:
Hyper_pred=Hyper_model.predict(X_train)
Hyper_acc=accuracy_score(Hyper_pred,y_train)
Hyper_acc

0.940279542566709

In [70]:
Hyper_Test_pred=Hyper_model.predict(X_test)
Hyper_Test_acc=accuracy_score(Hyper_Test_pred,y_test)
Hyper_Test_acc

0.9695431472081218